node('docker') {
  stage('Checkout'){
    checkout scm
  }
  stage('Fetch'){
    sh 'cd catanie && git clone https://github.com/SciCatProject/catanie.git'
    sh 'cd ..'
	sh 'cd catamel && git clone https://github.com/SciCatProject/catamel.git'
    sh 'cd ..'
	sh 'cd scicatingest && git clone https://github.com/garethcmurphy/scicatingest.git'
    sh 'cd ..'
  }
  stage('Build'){
    sh 'make'
  }
  stage('Run'){
    sh 'docker-compose run scicatingest '
  }
}
